config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'private_people', to: 'users/registrations#new_private_person'
    post 'private_people', to: 'users/registrations#create_private_person'
  end

  root to: "texts#index"
  resources :forms
  resources :users, only: [:show]
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_form, only: [:show, :edit, :update, :destroy]
  before_action :move_to_index, except: [:index, :new, :create]

  def index
    @forms = Form.all
  end
  
  def new
    @form = Form.new
  end

  def create
    @form = Form.new(form_params)
    if @form.save
      redirect_to user_path(current_user.id)
    else
      render :new
    end
  end

  def show
    @forms = Form.all
  end

  def edit
  end


  def update
    if @form.update(form_params)
      redirect_to forms_path
    else
      render :edit
    end
  end

  def destroy
    if @form.destroy
      redirect_to forms_path
    end
  end
  
  private

  def set_form
    @form = Form.find(params[:id])
  end

  def form_params
    params.require(:form).permit(:title, :content, :start_time, :image).merge(user_id: current_user.id)
  end
  
  def move_to_index
    unless user_signed_in? && current_user.id == @form.user.id
      redirect_to action: :index
    end
  end

end

app/helpers/forms_helper.rb
module FormsHelper
end

app/views/forms/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">日記編集</h2>
      <%= form_with model: @form, local: true do |f|%>
            <div class="field">
              <%= f.label :title, "Title" %><br />
              <%= f.text_field :title, id:"form_title", class: "field_top" %>
            </div>
            <br>
            <br>
            <div class="field">
              <%= f.label :content, "編集して下さい" %><br />
              <%= f.text_area :content, class: :form__text, id:"form_content", class: "field_content" %>
            </div>
            <br>
            <br>
            <div class="time">
                  <%= f.label :start_time %>
                  <%= f.datetime_select :start_time %>
            </div>
            <div class="field-image">
              <%= f.label :image, "投稿の画像" %><br />
              <%= f.file_field :image, id:"form_image", class:"field_buttom" %>
            </div>

            <div class="actions">
              <%= f.submit "投稿を保存する", class: :form__btn  %>
            </div>

      <% end %>
    </div>
    <br>
    <br>
    <br>
  </div>
</div>

app/views/forms/index.html.erb
<body>
    <div class="main-2">
      <div class="main-header">
          <div class="left-header">
            <%= link_to "RELAXATION DAIRY", root_path, class: "main-title" %>
          </div>
          <div class="right-header">
            <li><%= link_to 'マイページ', user_path(current_user.id), class: "my-page" %></li>
            <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "log-ou" %></li>
          </div>
      </div>
        <div class="simple-calender">
                <div class="calender">
                    <%= month_calendar events: @forms do |date, forms| %>
                        <%= date.day %>
                          <% forms.each do |form| %>
                            <% if current_user.id == form.user_id && form.title %>
                              <div>
                                <%= link_to form.title, form %>
                              </div>
                            <% end %>
                          <% end %>
                    <% end %>
                </div>
        </div>
        <div class="link">
          <%= link_to "Writing the Page", new_form_path, class: "write" %>
        </div>
            <br>
            <br>
          <div class="lesson-wrapper">
              <div class="heading">
                <h2>このアプリケーションの日記の書き方</h2>
              </div>
                <div class="explain">
                  <h3>免疫力が高まる３行日記</h3>
                  <div class="explain-title">
                    1 今日一番、自分が失敗したこと<br>
                  </div>
                    <p class="sentence">
                      失敗したことを書き出すことで客観視できるようになる。<br>
                      ストレスの原因と向き合うための一行。       
                    </p>
                  <div class="explain-title">
                    2 今日一番、自分が感動したこと。
                  </div>
                    <p class="sentence">
                      決して嫌なことばかりではないことに気づき、<br>
                      小さな感動を見つける完成を維持していくための一行。
                    </p>
                  <div class="explain-title">
                    3 明日の自分の目標
                  </div>
                    <p class="sentence">
                    未来に向けたビジョンを具体的にイメージしながら<br>
                    モチベーションを高める。
                    </p>
                </div>
                <%= render "shared/footer" %>
          </div>
        </div>
    </div>
</body>

app/views/forms/new.html.erb
<div class="head-image">
    <br>
    <br>
    <div class="container">
        <div class="col-sm-8 offset-sm-2">
          <div class="top-header">
            <p class="top-message">ここは完全にプライベートの部屋です。
              <br>何を書いても誰にも見られません。安心して好き放題書いて下さい。
            </p>
          </div>
    </div>
    <br>
    <div class="music">
        <audio controls preload="auto">
          <source src="https://hakuhin.jp/download/js/audio/sample_00.m4a" type="audio/mp4">
        </audio>
    </div>
    <div class="main">
        <div class="inner">
          <div class="form__wrapper">
            <div class="dairy">新規作成</div>
            <br>
              <%= form_with model: @form, local: true do |f|%>
                <div class="field">
                  <%= f.label :title, "Title" %><br />
                  <%= f.text_field :title, id:"form_title", class: "field_top"%>
                </div>
                <br>
                <br>
                <div class="field">
                  <%= f.label :content, "Please relax and write" %><br />
                  <br>
                  <%= f.text_area :content, class: :form__text, id:"form_content", class: "field_content",
                  placeholder: "５分以内に書き終えて下さい。" %>
                </div>
                <br>
                <br>
                <div class="time">
                     <%= f.label :start_time, "日付" %>
                     <%= f.datetime_select :start_time, class: "time-content" %>
                </div>
                <br>
                <div class="field-image">
                  <%= f.label :image, "投稿の画像" %><br />
                  <%= f.file_field :image, id:"form_image", class:"field_buttom" %>
                </div>
                <br>
                <div class="actions">
                  <%= f.submit "投稿を保存する", class: :form_btn  %>
                </div>
                <br>
              <% end %>
          </div>
        </div>
    </div>
    <div class="container">
        <div class="footer-content">
            <h1 class="footer-word">お疲れさまでした。</h1>
            <p class="footer-word">後日に見返してみましょう。</p>
    <br>
    <br>
        </div>
        <div class="row">
          <div class="footer-buttom">
            <%= link_to "HOMEへ戻る", forms_path, class: "back" %>//
          </div>
        </div>
    </div>
    <br>
</div>

app/views/forms/show.html.erb
  <div class="main-2">
    <div class="page-heading">
            <%= "#{@form.user.name}さんの日記投稿"%>
    </div>
    <div class="inner">
      <div class="user_wrapper">
        <div class="left-page">
              <table class="table">
                <tbody class="table-main">
                  <tr>
                    <th class="table__col1">投稿日時</th>
                    <td class="table__col2"><%=  @form.start_time.strftime("%Y-%m-%d %H:%M") %></td>
                  </tr>
                  <tr>
                    <th class="table__col1">タイトル</th>
                    <td class="table__col2"><%= @form.title %></td>
                  </tr>
                  <tr>
                    <th class="table__col1">コメント</th>
                    <td class="table__col2"><%=  @form.content %></td>
                  </tr>
                </tbody>
              </table>
        </div>
          <div class="right-page">
            <div class="page-phote">
            <%= image_tag(@form.image.variant(resize: '500x500')) if @form.image.attached? %>
            </div>
          </div>
      </div>
          <div class="edit-part">
            <div class="main-edit">
              <%= link_to "編集", edit_form_path(@form.id)%> /
              <%= link_to "削除", form_path(@form.id), method: :delete, class: :form__btn %>
            </div>
          </div>
        <div class="footer-bottom">
            <%= link_to "トップページに戻る", forms_path %>
        </div>
      </div>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
    </div>
  </div>