config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'private_people', to: 'users/registrations#new_private_person'
    post 'private_people', to: 'users/registrations#create_private_person'
  end

  root to: "texts#index"
  resources :forms
  resources :users, only: [:show]
end

app/models/text.rb
class Text < ApplicationRecord
end

app/controllers/texts_controller.rb
class TextsController < ApplicationController
  def index
  end
end

app/helpers/texts_helper.rb
module TextsHelper
end

app/views/texts/index.html.erb
<body>
  <div class="container">
      <div class="main-1">
          <% if user_signed_in? %>
            <div class="main">
              <div class="top-1">
                <div class="head-message">
                  <div class="title">
                    <span>ロ</span>
                    <span>グ</span>
                    <span>イ</span>
                    <span>ン</span>
                    <span>完</span>
                    <span>了</span>
                    <span>し</span>
                    <span>ま</span>
                    <span>し</span>
                    <span>た</span>
                    <span>。</span>
                  </div> 
                </div>
                  <div class="context">
                    <%=  "#{current_user.name}さん" %>
                  </div>
                  <p class="lead"><br>今日あったことを振り返りましょう。<br>
                  <br>
                    1, 今日一番自分が失敗したこと。<br>
                    <br>
                    2, 今日一番感動したこと。<br>
                    <br>
                    3, 明日の自分の目標。<br>
                  </p>
                  <div class="log-main">
                      <div class="enter">
                        <%= link_to "Enter the Room",  forms_path, class: "enter-btn" %>
                      </div>
                      <div class="log-out">
                        <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "btn2" %>
                      </div>
                  </div>
                </div>
            </div>
          <% else %>
            <div class="main">
                <br>
                <br>
                <br>
                <br>
                <br>
                <br>
                <br>
                <br>
                <div class="title">
                    <span>RELAXATION DAIRY</span>
                  </div>   
                <div class="content">
                  <div class="title">
                    <span>今</span>
                    <span>日</span>
                    <span>も</span>
                    <span>１</span>
                    <span>日</span>
                    <span>お</span>
                    <span>疲</span>
                    <span>れ</span>
                    <span>さ</span>
                    <span>ま</span>
                    <span>で</span>
                    <span>し</span>
                    <span>た</span>
                    <span>。</span>
                  </div> 
                </div>          
                    <div class="log">
                      <%= link_to "新規登録", new_user_registration_path %> /
                      <%= link_to "ログイン", new_user_session_path%>
                    </div>
              </div>
            </div>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
          <% end %>
      </div>
      <%= render "shared/footer" %>
  </div>
</body>